
/**
 * @brief Simulation class representing the execution of ray tracing and gas-surface interaction simulations.
 *
 * This class handles the propagation of rays in a defined domain, simulating the interactions between gas particles
 * and surfaces. It manages parameters such as the number of rays, child rays, and bounces, and defines the
 * behavior for various simulation steps.
 *
 * @tparam T Type used for values in the simulation (e.g., float, double).
 */
template <typename T>
class Simulation {

    private:
        unsigned long num_rays;           ///< Total number of rays in the simulation.
        unsigned int num_children;        ///< Number of child rays generated from each ray.
        unsigned int max_num_bounces;     ///< Maximum number of bounces allowed for each ray.
        void (*kernel)(T*, T*, T*, const Gas<T>&, Surface<T>&);  ///< Pointer to the kernel function modeling gas-surface interaction.

        Geometry<T> satellite;            ///< Geometry object representing the satellite or object in the domain.
        Surface<T> surface;               ///< Surface object representing the interaction surface for the rays.
        Domain<T> domain;                 ///< Domain object representing the environment where the simulation occurs.

    public:
        /**
         * @brief Default constructor for Simulation.
         */
        Simulation();

        /**
         * @brief Parameterized constructor for initializing a Simulation object with specific settings.
         *
         * @param domain The simulation domain representing the environment.
         * @param satellite The geometry of the object (e.g., satellite) in the simulation.
         * @param surface The surface object representing the target surface for interaction.
         * @param kernel Pointer to the function modeling gas-surface interaction.
         * @param num_rays Total number of rays to be simulated.
         * @param num_children Number of child rays generated for each ray.
         * @param num_bounces Maximum number of bounces a ray can undergo.
         */
        Simulation(Domain<T> domain, Geometry<T>& satellite, Surface<T> surface, void (*kernel)(T*, T*, T*, const Gas<T>&, Surface<T>&), unsigned long num_rays, unsigned int num_children, unsigned int num_bounces);

        /**
         * @brief Copy constructor.
         *
         * @param other Another Simulation object to copy from.
         */
        Simulation(const Simulation<T>& other);

        /**
         * @brief Move constructor.
         *
         * @param other Another Simulation object to move from.
         */
        Simulation(Simulation<T>&& other);

        /**
         * @brief Destructor.
         */
        ~Simulation();

        /**
         * @brief Copy assignment operator.
         *
         * @param other Another Simulation object to copy from.
         * @return Simulation& Reference to the updated object.
         */
        Simulation& operator=(const Simulation<T>& other);

        /**
         * @brief Move assignment operator.
         *
         * @param other Another Simulation object to move from.
         * @return Simulation& Reference to the updated object.
         */
        Simulation& operator=(Simulation<T>&& other);

        /**
         * @brief Getter for the number of rays in the simulation.
         *
         * @return unsigned long The total number of rays.
         */
        unsigned long get_num_rays() { return num_rays; }

        /**
         * @brief Getter for the number of child rays generated per ray.
         *
         * @return unsigned long The number of child rays.
         */
        unsigned long get_num_children() { return num_children; }

        /**
         * @brief Getter for the maximum number of bounces allowed per ray.
         *
         * @return unsigned long The maximum number of bounces.
         */
        unsigned long get_max_bounces() { return max_num_bounces; }

        /**
         * @brief Getter for the geometry object.
         *
         * @return Geometry<T>& Reference to the geometry object representing the satellite or object in the domain.
         */
        Geometry<T>& get_geometry() { return satellite; }

        /**
         * @brief Getter for the surface object.
         *
         * @return Surface<T>& Reference to the surface object.
         */
        Surface<T>& get_surface() { return surface; }

        /**
         * @brief Getter for the domain object.
         *
         * @return Domain<T>& Reference to the domain object representing the environment.
         */
        Domain<T>& get_domain() { return domain; }

        /**
         * @brief Computes the force generated by a ray bounce event.
         *
         * @param in_ray The incoming ray before the bounce.
         * @param child_rays The child rays resulting from the bounce.
         * @param geometry The geometry object involved in the bounce.
         * @return Matrix<T> The force generated by the ray bounce.
         */
        Matrix<T> compute_bounce_force(Ray<T>& in_ray, std::vector<Ray<T>>& child_rays, Geometry<T>& geometry);

        /**
         * @brief Computes the moment generated by a ray bounce event.
         *
         * @param in_ray The incoming ray before the bounce.
         * @param child_rays The child rays resulting from the bounce.
         * @param geometry The geometry object involved in the bounce.
         * @return Matrix<T> The moment generated by the ray bounce.
         */
        Matrix<T> compute_bounce_moment(Ray<T>& in_ray, std::vector<Ray<T>>& child_rays, Geometry<T>& geometry);

        /**
         * @brief Computes the shear coefficient based on force and the collision index.
         *
         * @param force_coefficient The computed force coefficient.
         * @param collision_index The index of the collision point.
         * @return Matrix<T> The shear coefficient matrix.
         */
        Matrix<T> compute_shear_coefficient(Matrix<T>& force_coefficient, unsigned int collision_index);

        /**
         * @brief Computes the pressure coefficient based on force and the collision index.
         *
         * @param force_coefficient The computed force coefficient.
         * @param collision_index The index of the collision point.
         * @return T The computed pressure coefficient.
         */
        T compute_pressure_coefficient(Matrix<T>& force_coefficient, unsigned int collision_index);

        /**
         * @brief Traces the propagation of rays through the domain and computes forces and moments.
         *
         * @param kernel Pointer to the gas-surface interaction model function.
         * @param current_rays The current set of rays to propagate.
         * @param norm_coeff Pointer to the normal force coefficient.
         * @param shear_x_coeff Pointer to the x-component of the shear force coefficient.
         * @param shear_y_coeff Pointer to the y-component of the shear force coefficient.
         * @param shear_z_coeff Pointer to the z-component of the shear force coefficient.
         * @return std::tuple<std::vector<Ray<T>>, Matrix<T>, Matrix<T>> A tuple containing updated rays, force matrix, and moment matrix.
         */
        std::tuple<std::vector<Ray<T>>, Matrix<T>, Matrix<T>> trace(void (*kernel)(T*, T*, T*, const Gas<T>&, Surface<T>&), std::vector<Ray<T>>& current_rays, T* norm_coeff, T* shear_x_coeff, T* shear_y_coeff, T* shear_z_coeff);

        /**
         * @brief Runs the full simulation and computes forces, moments, and coefficients.
         *
         * @return std::tuple<Matrix<T>, Matrix<T>> A tuple containing the force matrix, moment matrix, and various force/shear coefficients.
         */
        std::tuple<Matrix<T>, Matrix<T>> simulate(T* norm_coeff, T* shear_x_coeff, T* shear_y_coeff, T* shear_z_coeff);

        /**
         * @brief Runs the simulation in parallel for a subset of rays.
         *
         * @param start_index The starting index of the ray subset.
         * @param end_index The ending index of the ray subset.
         * @return std::tuple<Matrix<T>, Matrix<T>> A tuple containing the force matrix, moment matrix, and various force/shear coefficients for the subset.
         */
        std::tuple<Matrix<T>, Matrix<T>> simulate_parallel(int start_index, int end_index, T* norm_coeff, T* shear_x_coeff, T* shear_y_coeff, T* shear_z_coeff);

        /**
         * @brief Performs batch analysis for a range of angles of attack and sideslip angles.
         *
         * @param kernel Pointer to the gas-surface interaction model function.
         * @param min_AoA Minimum angle of attack.
         * @param max_AoA Maximum angle of attack.
         * @param step_AoA Step size for the angle of attack.
         * @param min_sideslip Minimum sideslip angle.
         * @param max_sideslip Maximum sideslip angle.
         * @param step_sideslip Step size for the sideslip angle.
         * @return std::tuple<std::vector<T>, std::vector<T>, std::vector<Matrix<T>>, std::vector<Matrix<T>>> A tuple containing angles of attack, sideslip angles, force matrices, and moment matrices.
         */
        std::tuple<std::vector<T>, std::vector<T>, std::vector<Matrix<T>>, std::vector<Matrix<T>>> batch_analysis(void (*kernel)(T*, T*, T*, const Gas<T>&, Surface<T>&), T min_AoA, T max_AoA, T step_AoA, T min_sideslip, T max_sideslip, T step_sideslip);
};


template <typename T>
Simulation<T>::Simulation() : num_rays(0), num_children(0), max_num_bounces(0) {}

template <typename T>
Simulation<T>::Simulation(Domain<T> domain, Geometry<T>& satellite, Surface<T> surface, void (*kernel)(T*, T*, T*, const Gas<T>&, Surface<T>&), unsigned long num_rays, unsigned int num_children, unsigned int num_bounces)
: domain(domain), satellite(satellite), surface(surface), kernel(kernel), num_rays(num_rays), num_children(num_children), max_num_bounces(num_bounces) {}

template <typename T>
Simulation<T>::Simulation(const Simulation<T>& other)
: num_rays(other.num_rays), num_children(other.num_children), max_num_bounces(other.max_num_bounces), satellite(other.satellite), surface(other.surface), domain(other.domain), kernel(other.kernel) {}

template <typename T>
Simulation<T>::Simulation(Simulation<T>&& other)
: num_rays(other.num_rays), num_children(other.num_children), max_num_bounces(other.max_num_bounces), satellite(other.satellite), surface(other.surface), domain(other.domain), kernel(other.kernel) {
    other.num_rays = 0;
    other.num_children = 0;
    other.max_num_bounces = 0;
}

template <typename T>
Simulation<T>& Simulation<T>::operator=(const Simulation<T>& other) {
    num_rays = other.num_rays;
    num_children = other.num_children;
    max_num_bounces = other.max_num_bounces;
    satellite = other.satellite;
    surface = other.surface;
    domain = other.domain;
    kernel = other.kernel;

    return *this;
}

template <typename T>
Simulation<T>& Simulation<T>::operator=(Simulation<T>&& other) {
    num_rays = other.num_rays;
    num_children = other.num_children;
    max_num_bounces = other.max_num_bounces;
    satellite = other.satellite;
    surface = other.surface;
    domain = other.domain;
    kernel = other.kernel;

    other.num_rays = 0;
    other.num_children = 0;
    other.max_num_bounces = 0;

    return *this;
}

template <typename T>
Simulation<T>::~Simulation() {
    num_rays = 0;
    num_children = 0;
    max_num_bounces = 0;
}

template <typename T>
Matrix<T> Simulation<T>::compute_bounce_force(Ray<T>& in_ray, std::vector<Ray<T>>& child_rays, Geometry<T>& geometry) {
    Matrix<T> C_F(3, 1, {0.0, 0.0, 0.0});
    Matrix<T> v_in = in_ray.get_velocity();
    T m_dot_in = in_ray.get_mass_flux();

    if (child_rays.size() == 0) return C_F;

    for(auto i = 0; i < child_rays.size(); i ++) {
        
        Matrix<T> v_refl = child_rays[i].get_velocity();
        T m_dot_refl = child_rays[i].get_mass_flux();

        C_F += (v_refl * v_refl.norm() * m_dot_refl) / pow(domain.get_gas_speed_magnitude(), 2) / geometry.get_A_ref() * 2.0;
    }

    C_F -= (v_in * v_in.norm() * m_dot_in) / pow(domain.get_gas_speed_magnitude(), 2) / geometry.get_A_ref() * 2.0;

    return C_F;
}

template <typename T>
Matrix<T> Simulation<T>::compute_bounce_moment(Ray<T>& in_ray, std::vector<Ray<T>>& child_rays, Geometry<T>& geometry) {
    Matrix<T> C_M(3, 1);
    Matrix<T> moment_arm = child_rays[0].get_origin();
    Matrix<T> v_in = in_ray.get_velocity();
    T m_dot_in = in_ray.get_mass_flux();

    if (child_rays.size() == 0) return C_M;

    for(auto i = 0; i < child_rays.size(); i ++) {
       
        Matrix<T> v_refl = child_rays[i].get_velocity();
        T m_dot_refl = child_rays[i].get_mass_flux();

        C_M += moment_arm.cross((v_refl * m_dot_refl * v_refl.norm()) / pow(domain.get_gas_speed_magnitude(), 2) / geometry.get_A_ref() / geometry.get_c_ref()) * 2.0;
    }
    C_M -= moment_arm.cross((v_in * m_dot_in * v_in.norm()) / pow(domain.get_gas_speed_magnitude(), 2) / geometry.get_A_ref() / geometry.get_c_ref()) * 2.0; 
    
    return C_M;
}

template <typename T>
Matrix<T> Simulation<T>::compute_shear_coefficient(Matrix<T>& force_coefficient, unsigned int collision_index) {

    Matrix<T> shear_coefficient(3, 1);
    Matrix<T> normal(3, 1, {satellite.get_norm_x()(collision_index), satellite.get_norm_y()(collision_index), satellite.get_norm_z()(collision_index)});

    shear_coefficient = (force_coefficient - (normal * force_coefficient.tr().dot(normal)(0, 0))) / satellite.compute_area(collision_index);

    return shear_coefficient;
}

template <typename T>
T Simulation<T>::compute_pressure_coefficient(Matrix<T>& force_coefficient, unsigned int collision_index) {
    Matrix<T> normal(3, 1, {satellite.get_norm_x()(collision_index), satellite.get_norm_y()(collision_index), satellite.get_norm_z()(collision_index)});

    T pressure_coefficient = force_coefficient.tr().dot(normal)(0, 0) ;/// satellite.compute_area(collision_index);

    return pressure_coefficient;
}

template <typename T>
std::tuple<std::vector<Ray<T>>, Matrix<T>, Matrix<T>> Simulation<T>::trace(void (*kernel)(T*, T*, T*, const Gas<T>&, Surface<T>&), std::vector<Ray<T>>& current_rays, T* norm_coeff, T* shear_x_coeff, T* shear_y_coeff, T* shear_z_coeff) {
    
    std::vector<Ray<T>> new_rays;
    Matrix<T> C_F_new(3, 1);
    Matrix<T> C_M_new(3, 1);
    
    for(auto i = 0; i < current_rays.size(); i ++) {
        unsigned int collision_index;
        std::vector<Ray<T>> child_rays = current_rays[i].propagate(satellite, surface, domain.get_atmosphere(), kernel, &collision_index);

        if (child_rays.size() > 0) {
            Matrix<T> C_F_local = compute_bounce_force(current_rays[i], child_rays, satellite);
            Matrix<T> C_M_local = compute_bounce_moment(current_rays[i], child_rays, satellite);

            C_F_new += C_F_local;
            C_M_new += C_M_local;

            norm_coeff[collision_index] += compute_pressure_coefficient(C_F_local, collision_index);
            Matrix<T> shear(3, 1);
            shear = compute_shear_coefficient(C_F_local, collision_index);
            shear_x_coeff[collision_index] += shear(0, 0);
            shear_y_coeff[collision_index] += shear(1, 0);
            shear_z_coeff[collision_index] += shear(2, 0);

            new_rays.insert(std::end(new_rays), std::begin(child_rays), std::end(child_rays));
            
        }
        std::vector<Ray<T>>().swap(child_rays);
    }
    current_rays.clear();
    
    return std::make_tuple(new_rays, C_F_new, C_M_new);
}

template <typename T>
std::tuple<Matrix<T>, Matrix<T>> Simulation<T>::simulate(T* norm_coeff, T* shear_x_coeff, T* shear_y_coeff, T* shear_z_coeff) {

    std::vector<Ray<T>> rays = domain.generate_rays(num_rays, num_children);
    Matrix<T> C_F(3, 1);
    Matrix<T> C_M(3, 1);
    
    for(auto i = 0; i < max_num_bounces; i ++) {
        std::tuple<std::vector<Ray<T>>, Matrix<T>, Matrix<T>> trace_results = trace(kernel, rays, norm_coeff, shear_x_coeff, shear_y_coeff, shear_z_coeff);
        rays = std::get<0>(trace_results);
        C_F += std::get<1>(trace_results);
        C_M += std::get<2>(trace_results);
    }
    return std::make_tuple(C_F, C_M);
}

template <typename T>
std::tuple<Matrix<T>, Matrix<T>> Simulation<T>::simulate_parallel(int start_index, int end_index, T* norm_coeff, T* shear_x_coeff, T* shear_y_coeff, T* shear_z_coeff) {

    std::vector<Ray<T>> rays = domain.generate_rays_parallel(num_rays, start_index, end_index, num_children);
    Matrix<T> C_F(3, 1);
    Matrix<T> C_M(3, 1);
    
    for(auto i = 0; i < max_num_bounces; i ++) {
        std::tuple<std::vector<Ray<T>>, Matrix<T>, Matrix<T>> trace_results = trace(kernel, rays, norm_coeff, shear_x_coeff, shear_y_coeff, shear_z_coeff);
        rays = std::get<0>(trace_results);
        C_F += std::get<1>(trace_results);
        C_M += std::get<2>(trace_results);
    }

    return std::make_tuple(C_F, C_M);
}

